@startuml name
[*]   --> ログイン画面 : 最初にログイン画面に飛ぶ
ログイン画面  --> 登録 : 登録ボタンを押すと登録画面に飛ぶ
ログイン画面 : ID
ログイン画面 : パスワード

ログイン画面 --> 掲示板 : ログイン画面から掲示板に飛ぶとログイン画面に飛ぶ
掲示板 : 記事一覧
掲示板 : 投稿者一覧
掲示板:ユーザー情報の変更
掲示板 : ログアウト

ログイン画面 --> ログイン画面 : 登録してログインしてから、掲示板に飛ぶ

登録 --> ログイン画面 : 登録するとログイン画面に飛ぶ
登録 : アイコン
登録 : ログインID
登録 : パスワード
登録 : 名前

掲示板 --> 投稿ページ 
投稿ページ: 画像
投稿ページ : 題名
投稿ページ : 内容

掲示板-->投稿記事
投稿記事:編集
投稿記事:削除
投稿記事:コメント
投稿記事:投稿日時
投稿記事:いいね

投稿記事-->編集
編集:編集ボタン

編集-->投稿記事 : 編集すると投稿記事に戻る

投稿記事-->削除
削除:削除ボタン

削除-->投稿記事 : 削除すると投稿記事に戻る

投稿記事-->コメント
コメント:

コメント-->投稿記事 : コメントすると投稿記事に戻る 

掲示板 --> 投稿者一覧
投稿者一覧 : 投稿者A
投稿者一覧 : 投稿者B
投稿者一覧 : 投稿者C
投稿者一覧 : 投稿者D

掲示板-->ログアウト
ログアウト:ログアウトボタン

投稿者一覧 --> 選択した投稿者
選択した投稿者 : 今まで投稿した記事